# Generated by Django 6.0.5 on 2026-06-12 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_admin', '0001_initial'),
        ('super_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='super_admin.institution'),
        ),
        migrations.AddField(
            model_name='branchrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_branch_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchrequest',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_requests', to='super_admin.institution'),
        ),
        migrations.AddField(
            model_name='customrole',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='super_admin.institution'),
        ),
        migrations.AddField(
            model_name='schooladminprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='super_admin.institution'),
        ),
        migrations.AddField(
            model_name='schooladminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school_admin.branch'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='school_admin.branch'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_admin.branch'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school_admin.branch'),
        ),
    ]
