# Generated by Django 6.0.5 on 2026-06-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_schoolclass'),
        ('super_admin', '0003_institution_activation_requested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='super_admin.institution')),
            ],
        ),
    ]
