# Generated by Django 6.0.5 on 2026-06-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='plan',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='school_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
