# Generated by Django 6.0.5 on 2026-06-10 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_institution_plan_institution_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='activation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='super_admin.inquiry'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='super_admin.inquiry'),
        ),
    ]
